apiVersion: v1
kind: Namespace
metadata:
  name: golang-packr-demo

---

apiVersion: v1
kind: Service
metadata:
  name: golang-packr-demo-service
  namespace: golang-packr-demo
  labels:
    app: golang-packr-demo-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: app-port
      protocol: TCP
      name: http
  selector:
    app: golang-packr-demo-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-packr-demo-app
  namespace: golang-packr-demo
  labels:
    app: golang-packr-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-packr-demo-app
  template:
    metadata:
      labels:
        app: golang-packr-demo-app
    spec:
      containers:
        - name: golang-packr-demo-app
          image: cflynnus/golang-packr-demo
          env:
            - name: PORT
              value: "80"
          ports:
            - name: app-port
              containerPort: 80
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
